name: Build LiteLoaderPlugins

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  Platform: X64
  ChakraCore_version: cc_windows_all_1_11_24

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - name: Download Lib from server
      run: |
        curl -L -o D:/lib.zip https://github.com/LiteLDev/Resources/raw/main/lib.zip
        unzip D:/lib.zip -d Lib/
        rm D:/lib.zip
      shell: bash
     
    - name: Download Libraries
      run: |
        curl -L -o D:/plugin-lib.zip https://sqlite.org/2021/sqlite-dll-win64-x64-3340100.zip
        mkdir D:/lib
        unzip D:/plugin-lib.zip -d D:/lib
        rm D:/lib.zip
      shell: bash

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        MSBuild.exe ./LiteLoaderMOD.sln -property:Configuration=Release
      shell: bash
    
    - name: MkDirs
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir D:/out/sdk
        mkdir D:/out/sdk/lib
        mkdir D:/out/sdk/headers
        mkdir D:/out/plugins
        mkdir D:/out/plugins/lib
    
    - name: Copy Out Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cp x64/Release/*.dll D:/out/plugins
        cp x64/Release/*.lib D:/out/sdk/lib
        cp x64/Release/*.pdb D:/out/plugins
        cp headers/LLMoney.h D:/out/sdk/headers
        cp -r plugins/* D:/out/plugins
        cp D:/lib/*.dll D:/out/plugins/lib
      shell: bash

    - name: Upload plugins
      uses: actions/upload-artifact@v1.0.0
      with:
        name: plugins
        path: D:/out/plugins

    - name: Upload SDK
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SDK
        path: D:/out/sdk

    - name: Compress to zip
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        7z a D:/out/plugins.zip D:/out/plugins
        7z a D:/out/sdk.zip D:/out/sdk
      shell: bash

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}\CHANGELOG.txt
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        files: |
          D:/out/plugins.zip
          D:/out/sdk.zip
      env:
          GITHUB_REPOSITORY: LiteLDev/LiteLoaderPlugins
