name: Build LiteLoaderKit

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  Platform: X64
  ChakraCore_version: cc_windows_all_1_11_24

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        MSBuild.exe ./LiteLoaderMOD.sln -property:Configuration=Release
      shell: bash
    
    - name: MkDirs
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir D:/out/lib
        mkdir D:/out/headers
        mkdir D:/out/plugins/LLMoney/langpack
    
    - name: Copy Out Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cp x64/Release/*.dll D:/out/plugins
        cp x64/Release/*.lib D:/out/lib
        cp headers/LLMoney.h D:/out/headers
        cp -r plugins/LLMoney/ D:/out/
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: LiteLoaderKit
        path: D:/out
